name: bmad-odoo-dev
version: 1.2.0
short-title: Odoo ERP Development Pack
description: >-
  This expansion pack extends BMad Method with comprehensive Odoo ERP development
  capabilities. It's designed for teams that need to define, implement, and manage
  Odoo modules, customizations, and integrations using Doodba deployment patterns
  and OCA community standards.
author: BMad Community
slashPrefix: BMadOdooDev
category: domain-specific
domain: odoo-development
framework: doodba
community: oca

# Odoo-specific configuration
odoo:
  supportedVersions: [13.0, 14.0, 15.0, 16.0, 17.0, 18.0]
  deployment: doodba
  community: oca
  focus: brownfield
  
# Integration settings
integration:
  inheritsFrom: bmad-method
  extendsCore: true
  standalone: false
  
# Available agents
agents:
  - name: odoo-functional-consultant
    file: agents/odoo-functional-consultant.md
    role: Business process analysis and requirements gathering
  - name: odoo-technical-architect
    file: agents/odoo-technical-architect.md
    role: System architecture and technical design
  - name: odoo-developer
    file: agents/odoo-developer.md
    role: Implementation and coding guidance
  - name: odoo-migration-specialist
    file: agents/odoo-migration-specialist.md
    role: Version migrations and upgrades
  - name: doodba-devops-expert
    file: agents/doodba-devops-expert.md
    role: Deployment and infrastructure management

# Available tasks
tasks:
  - name: create-odoo-addon
    file: tasks/create-odoo-addon.md
    description: Generate new Odoo addon from business requirements
  - name: enhance-existing-odoo-system
    file: tasks/enhance-existing-odoo-system.md
    description: Plan brownfield system enhancements
  - name: plan-odoo-migration
    file: tasks/plan-odoo-migration.md
    description: Structure version upgrade approach

# Available templates
templates:
  - name: odoo-prd-template
    file: templates/odoo-prd-template.yaml
    description: Product requirements for Odoo implementations
  - name: odoo-architecture-template
    file: templates/odoo-architecture-template.yaml
    description: Technical architecture for Odoo modules
  - name: odoo-story-template
    file: templates/odoo-story-template.yaml
    description: User story template for Odoo development

# File structure
structure:
  agents: agents/
  tasks: tasks/
  templates: templates/
  data: data/
  checklists: checklists/
  teams: teams/